export default JSON.parse(`[
  {
    "empNo": "2021002",
    "empNm": "양승현",
    "regNo": "9611021******",
    "sexTp": "10",
    "deptCd": "100",
    "rankCd": "02",
    "gradeCd": "02",
    "paystepCd": "001",
    "joinDt": "2020-03-09",
    "resignDt": null,
    "tenureTp": "20",
    "addr": "경기 고양시 덕양구 소원로 267 (행신동, 서정마을3단지아파트) 303-501",
    "telNo1": null,
    "mobilNo": null,
    "emailId": "yang0184@naver.com",
    "acdmTp": null,
    "regAddrH": "경기 고양시 덕양구 소원로 267 (행신동, 서정마을3단지아파트)",
    "regAddrD": "303-501",
    "sexTpNm": "남",
    "deptNm": "관리과",
    "rankNm": "주임",
    "regPostNo": "10534"
  },
  {
    "empNo": "2021004",
    "empNm": "고길동",
    "regNo": "7501011******",
    "sexTp": "10",
    "deptCd": "200",
    "rankCd": "02",
    "gradeCd": "02",
    "paystepCd": "001",
    "joinDt": "2019-01-01",
    "resignDt": null,
    "tenureTp": "20",
    "addr": " ",
    "telNo1": null,
    "mobilNo": null,
    "emailId": "weponemaster@test.io",
    "acdmTp": null,
    "regAddrH": null,
    "regAddrD": null,
    "sexTpNm": "남",
    "deptNm": "생산과",
    "rankNm": "주임",
    "regPostNo": null
  },
  {
    "empNo": "2021005",
    "empNm": "이강모",
    "regNo": "7601011******",
    "sexTp": "10",
    "deptCd": "200",
    "rankCd": "05",
    "gradeCd": "05",
    "paystepCd": "001",
    "joinDt": "2019-01-01",
    "resignDt": null,
    "tenureTp": "20",
    "addr": " ",
    "telNo1": null,
    "mobilNo": null,
    "emailId": null,
    "acdmTp": null,
    "regAddrH": null,
    "regAddrD": null,
    "sexTpNm": "남",
    "deptNm": "생산과",
    "rankNm": "수석",
    "regPostNo": null
  },
  {
    "empNo": "2021018",
    "empNm": "정강지",
    "regNo": "9411152******",
    "sexTp": "20",
    "deptCd": "100",
    "rankCd": "04",
    "gradeCd": "04",
    "paystepCd": "001",
    "joinDt": "2021-01-10",
    "resignDt": null,
    "tenureTp": "20",
    "addr": " ",
    "telNo1": null,
    "mobilNo": "01011112222",
    "emailId": "aaa@test.io",
    "acdmTp": null,
    "regAddrH": null,
    "regAddrD": null,
    "sexTpNm": "여",
    "deptNm": "관리과",
    "rankNm": "책임",
    "regPostNo": null
  },
  {
    "empNo": "2021019",
    "empNm": "김마뫄",
    "regNo": null,
    "sexTp": null,
    "deptCd": "100",
    "rankCd": "03",
    "gradeCd": "03",
    "paystepCd": "001",
    "joinDt": "2017-11-07",
    "resignDt": null,
    "tenureTp": "20",
    "addr": " ",
    "telNo1": null,
    "mobilNo": null,
    "emailId": null,
    "acdmTp": null,
    "regAddrH": null,
    "regAddrD": null,
    "sexTpNm": null,
    "deptNm": "관리과",
    "rankNm": "선임",
    "regPostNo": null
  },
  {
    "empNo": "2021021",
    "empNm": "김지누",
    "regNo": null,
    "sexTp": "10",
    "deptCd": "100",
    "rankCd": "03",
    "gradeCd": "03",
    "paystepCd": "001",
    "joinDt": "2020-05-14",
    "resignDt": null,
    "tenureTp": "20",
    "addr": "경기 고양시 일산동구 강석로 108 (마두동, 강촌마을5단지) ",
    "telNo1": null,
    "mobilNo": null,
    "emailId": null,
    "acdmTp": null,
    "regAddrH": "경기 고양시 일산동구 강석로 108 (마두동, 강촌마을5단지)",
    "regAddrD": null,
    "sexTpNm": "남",
    "deptNm": "관리과",
    "rankNm": "선임",
    "regPostNo": "10415"
  },
  {
    "empNo": "2021022",
    "empNm": "박수아",
    "regNo": "9903132******",
    "sexTp": "20",
    "deptCd": "100",
    "rankCd": "01",
    "gradeCd": "01",
    "paystepCd": "001",
    "joinDt": "2021-01-11",
    "resignDt": null,
    "tenureTp": "20",
    "addr": " ",
    "telNo1": null,
    "mobilNo": null,
    "emailId": null,
    "acdmTp": null,
    "regAddrH": null,
    "regAddrD": null,
    "sexTpNm": "여",
    "deptNm": "관리과",
    "rankNm": "사원",
    "regPostNo": null
  },
  {
    "empNo": "2021309",
    "empNm": "김똘복",
    "regNo": "9309131******",
    "sexTp": "10",
    "deptCd": "100",
    "rankCd": "01",
    "gradeCd": "01",
    "paystepCd": "001",
    "joinDt": "2021-02-10",
    "resignDt": null,
    "tenureTp": "20",
    "addr": " ",
    "telNo1": null,
    "mobilNo": null,
    "emailId": null,
    "acdmTp": null,
    "regAddrH": null,
    "regAddrD": null,
    "sexTpNm": "남",
    "deptNm": "관리과",
    "rankNm": "사원",
    "regPostNo": null
  },
  {
    "empNo": "2021393",
    "empNm": "최민규",
    "regNo": "9310271******",
    "sexTp": "10",
    "deptCd": "300",
    "rankCd": "02",
    "gradeCd": "02",
    "paystepCd": "001",
    "joinDt": "2020-05-08",
    "resignDt": null,
    "tenureTp": "20",
    "addr": " ",
    "telNo1": null,
    "mobilNo": null,
    "emailId": null,
    "acdmTp": null,
    "regAddrH": null,
    "regAddrD": null,
    "sexTpNm": "남",
    "deptNm": "요양과",
    "rankNm": "주임",
    "regPostNo": null
  },
  {
    "empNo": "2021395",
    "empNm": "견자희",
    "regNo": "9406112******",
    "sexTp": "20",
    "deptCd": "100",
    "rankCd": "05",
    "gradeCd": "05",
    "paystepCd": "001",
    "joinDt": "2021-03-19",
    "resignDt": null,
    "tenureTp": "20",
    "addr": " ",
    "telNo1": null,
    "mobilNo": null,
    "emailId": null,
    "acdmTp": null,
    "regAddrH": null,
    "regAddrD": null,
    "sexTpNm": "여",
    "deptNm": "관리과",
    "rankNm": "수석",
    "regPostNo": null
  },
  {
    "empNo": "2021397",
    "empNm": "이예은",
    "regNo": "9411302******",
    "sexTp": "20",
    "deptCd": "100",
    "rankCd": "01",
    "gradeCd": "01",
    "paystepCd": "001",
    "joinDt": "2021-01-05",
    "resignDt": null,
    "tenureTp": "20",
    "addr": " ",
    "telNo1": null,
    "mobilNo": null,
    "emailId": null,
    "acdmTp": null,
    "regAddrH": null,
    "regAddrD": null,
    "sexTpNm": "여",
    "deptNm": "관리과",
    "rankNm": "사원",
    "regPostNo": null
  },
  {
    "empNo": "2021398",
    "empNm": "데이나",
    "regNo": "9007152******",
    "sexTp": "20",
    "deptCd": "100",
    "rankCd": "01",
    "gradeCd": "01",
    "paystepCd": "001",
    "joinDt": "2021-01-04",
    "resignDt": null,
    "tenureTp": "20",
    "addr": " ",
    "telNo1": null,
    "mobilNo": null,
    "emailId": null,
    "acdmTp": null,
    "regAddrH": null,
    "regAddrD": null,
    "sexTpNm": "여",
    "deptNm": "관리과",
    "rankNm": "사원",
    "regPostNo": null
  },
  {
    "empNo": "2021399",
    "empNm": "김성윤",
    "regNo": "9705141******",
    "sexTp": "10",
    "deptCd": "100",
    "rankCd": "03",
    "gradeCd": "03",
    "paystepCd": "001",
    "joinDt": "2021-01-25",
    "resignDt": null,
    "tenureTp": "20",
    "addr": " ",
    "telNo1": null,
    "mobilNo": null,
    "emailId": null,
    "acdmTp": null,
    "regAddrH": null,
    "regAddrD": null,
    "sexTpNm": "남",
    "deptNm": "관리과",
    "rankNm": "선임",
    "regPostNo": null
  },
  {
    "empNo": "2021400",
    "empNm": "핑맨",
    "regNo": "9407181******",
    "sexTp": "10",
    "deptCd": "100",
    "rankCd": "04",
    "gradeCd": "04",
    "paystepCd": "001",
    "joinDt": "2021-02-02",
    "resignDt": null,
    "tenureTp": "20",
    "addr": " ",
    "telNo1": null,
    "mobilNo": null,
    "emailId": null,
    "acdmTp": null,
    "regAddrH": null,
    "regAddrD": null,
    "sexTpNm": "남",
    "deptNm": "관리과",
    "rankNm": "책임",
    "regPostNo": null
  },
  {
    "empNo": "2021401",
    "empNm": "김점례",
    "regNo": "9405162******",
    "sexTp": "20",
    "deptCd": "100",
    "rankCd": "06",
    "gradeCd": "06",
    "paystepCd": "001",
    "joinDt": "2021-02-02",
    "resignDt": null,
    "tenureTp": "20",
    "addr": " ",
    "telNo1": null,
    "mobilNo": null,
    "emailId": null,
    "acdmTp": null,
    "regAddrH": null,
    "regAddrD": null,
    "sexTpNm": "여",
    "deptNm": "관리과",
    "rankNm": "이사",
    "regPostNo": null
  },
  {
    "empNo": "2021442",
    "empNm": "끠끼",
    "regNo": "9603012******",
    "sexTp": "20",
    "deptCd": "100",
    "rankCd": "01",
    "gradeCd": "01",
    "paystepCd": "001",
    "joinDt": "2021-02-05",
    "resignDt": null,
    "tenureTp": "20",
    "addr": " ",
    "telNo1": null,
    "mobilNo": null,
    "emailId": null,
    "acdmTp": null,
    "regAddrH": null,
    "regAddrD": null,
    "sexTpNm": "여",
    "deptNm": "관리과",
    "rankNm": "사원",
    "regPostNo": null
  },
  {
    "empNo": "2022463",
    "empNm": "망개",
    "regNo": "0010154******",
    "sexTp": "20",
    "deptCd": "100",
    "rankCd": null,
    "gradeCd": null,
    "paystepCd": null,
    "joinDt": "2020-01-01",
    "resignDt": null,
    "tenureTp": "20",
    "addr": " ",
    "telNo1": null,
    "mobilNo": null,
    "emailId": null,
    "acdmTp": null,
    "regAddrH": null,
    "regAddrD": null,
    "sexTpNm": "여",
    "deptNm": "관리과",
    "rankNm": null,
    "regPostNo": null
  },
  {
    "empNo": "2023467",
    "empNm": "양원영",
    "regNo": "5808011******",
    "sexTp": "10",
    "deptCd": "100",
    "rankCd": "05",
    "gradeCd": "05",
    "paystepCd": "001",
    "joinDt": "2020-01-01",
    "resignDt": null,
    "tenureTp": "20",
    "addr": " ",
    "telNo1": null,
    "mobilNo": null,
    "emailId": null,
    "acdmTp": null,
    "regAddrH": null,
    "regAddrD": null,
    "sexTpNm": "남",
    "deptNm": "관리과",
    "rankNm": "수석",
    "regPostNo": null
  },
  {
    "empNo": "2023468",
    "empNm": "감블러",
    "regNo": "9711121******",
    "sexTp": "10",
    "deptCd": "100",
    "rankCd": "03",
    "gradeCd": "03",
    "paystepCd": "001",
    "joinDt": "2023-01-30",
    "resignDt": null,
    "tenureTp": "20",
    "addr": " ",
    "telNo1": null,
    "mobilNo": null,
    "emailId": null,
    "acdmTp": null,
    "regAddrH": null,
    "regAddrD": null,
    "sexTpNm": "남",
    "deptNm": "관리과",
    "rankNm": "선임",
    "regPostNo": null
  },
  {
    "empNo": "2023472",
    "empNm": "임나은",
    "regNo": "9807162******",
    "sexTp": "20",
    "deptCd": "100",
    "rankCd": "01",
    "gradeCd": "01",
    "paystepCd": "001",
    "joinDt": "2022-03-02",
    "resignDt": null,
    "tenureTp": "20",
    "addr": " ",
    "telNo1": null,
    "mobilNo": null,
    "emailId": null,
    "acdmTp": null,
    "regAddrH": null,
    "regAddrD": null,
    "sexTpNm": "여",
    "deptNm": "관리과",
    "rankNm": "사원",
    "regPostNo": null
  },
  {
    "empNo": "2023475",
    "empNm": "민결희",
    "regNo": "9502122******",
    "sexTp": "20",
    "deptCd": "100",
    "rankCd": "03",
    "gradeCd": "03",
    "paystepCd": "001",
    "joinDt": "2020-01-01",
    "resignDt": null,
    "tenureTp": "20",
    "addr": " ",
    "telNo1": null,
    "mobilNo": null,
    "emailId": null,
    "acdmTp": null,
    "regAddrH": null,
    "regAddrD": null,
    "sexTpNm": "여",
    "deptNm": "관리과",
    "rankNm": "선임",
    "regPostNo": null
  }
]`)
